### ISSUE TITLE
beforeRouteEnter is called multiple times

### ISSUE THREAD

**Issue by dmtkpv** [vuejs/router#1152]
### Version
4.0.11

### Reproduction link
[jsfiddle.net/kegdqcmz/](https://jsfiddle.net/kegdqcmz/)

### Steps to reproduce
1. Go to https://jsfiddle.net/kegdqcmz/
2. Open console
3. Click "Test"
4. Click "Test" again
5. Check console output

### What is expected?
beforeRouteEnter is called only once

### What is actually happening?
beforeRouteEnter is called multiple times

**Comment by dmtkpv** [comment]
The example demonstrates that `beforeRouteEnter` can be called multiple times. This results in extra API calls if route fetches data from the backend.

Example: https://jsfiddle.net/xgspe390/

To reproduce:
1. Click "Test"
2. Click "Test" again before the request is ended

**Comment by posva** [comment]
That is expected because you are triggering a new navigation while the ongoing navigation isn't over yet and that triggers a new fetch that takes long.
You can still cancel the new navigations if you want by saving the fact the you are fetching already **or** cancel the previous fetch with an abort signal. These two patterns are totally valid and it's up to you to choose.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
