### ISSUE TITLE
Beforerouteupdate()'s modification of {from} does not take effect

### ISSUE THREAD

**Issue by gangganghao6** [vuejs/router#1335]
### Version
4.0.13

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vug-router-4-0-12-forked-4fgkqm)

### Steps to reproduce
Switch routes multiple times Make sure that all sub routes have been modified by onBeforeRouteUpdate(), and then check the created() print of route meta attribute

### What is expected?
In created(), you can get the modification of route meta attribute  by onbeforerouteupdate()

### What is actually happening?
The modification result of onBeforeRouteUpdate() cannot be obtained in created(), which is still the initial value

---
Scenario: record some operations performed by the user before the page is switched
The modification of {to} in onBeforeRouteUpdate() takes effect, This modification is also effective in vue route 3.x

**Comment by posva** [comment]
This is expected because `meta` is now the merge of parent to child routes (Root and Home meta) and is refreshed at each navigation.
You can still rewrite the original route records in the `matched` array if you want but I discourage you from relying on this because in your case, you should instead save the state locally somewhere else.
