### ISSUE TITLE
Error in mounted hook breaks router.

### ISSUE THREAD

**Issue by suienzan** [vuejs/router#1395]
### Version
4.0.12

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vue3-vite-router-starter-ydd9bc)

### Steps to reproduce
1. Click link `Contact`. (Which has an error in mounted hook).
2. Click link `Home` or `About`.

### What is expected?
Render right page.

### What is actually happening?
Keep rendering `Contact` page

**Comment by posva** [comment]
This dev-only error is from Vue: using the code from [this playground](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgc2hhbGxvd1JlZiwgcHJvdmlkZSB9IGZyb20gJ3Z1ZSdcbiAgaW1wb3J0IFZpZXcgZnJvbSAnLi9WaWV3LnRzJ1xuICBpbXBvcnQgQ29tcCBmcm9tICcuL0NvbXAudnVlJ1xuICBpbXBvcnQgUGFnZUEgZnJvbSAnLi9QYWdlQS52dWUnXG4gIGltcG9ydCBQYWdlQiBmcm9tICcuL1BhZ2VCLnZ1ZSdcblxuXG5jb25zdCB2aWV3ID0gc2hhbGxvd1JlZihQYWdlQSlcbnByb3ZpZGUoJ3ZpZXcnLCB2aWV3KVxuICBcbiAgZnVuY3Rpb24gdG9nZ2xlVmlldygpIHtcbiAgICBjb25zdCBwID0gdmlldy52YWx1ZVxuICAgIHZpZXcudmFsdWUgPSBwID09PSBQYWdlQSA/IFBhZ2VCIDogcCA9PT0gUGFnZUIgPyBDb21wIDogUGFnZUFcbiAgfVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGJ1dHRvbiBAY2xpY2s9XCJ0b2dnbGVWaWV3KClcIj5cbiAgICBUb29nbGUgVmlld1xuICA8L2J1dHRvbj5cbiAgPFZpZXcgLz5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSIsIkNvbXAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcblxuICBvbk1vdW50ZWQoKCkgPT4ge1xuICAgIHRocm93IG5ldyBFcnJvcignZmFpbCEnKVxuICB9KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHA+XG4gICAgSSBmYWlsIG9uIG1vdW50XG4gIDwvcD5cbjwvdGVtcGxhdGU+IiwiVmlldy50cyI6ImltcG9ydCBDb21wIGZyb20gJy4vQ29tcC52dWUnXG5pbXBvcnQgeyBoLCByZWYsIGluamVjdCwgdmlld1JlZiwgd2F0Y2ggfSBmcm9tICd2dWUnXG5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgaW5oZXJpdEF0dHJzOiBmYWxzZSxcbiAgbmFtZTogJ1JvdXRlclZpZXcnLFxuICBzZXR1cCgpIHtcbiAgICBjb25zdCB2aWV3UmVmID0gcmVmKClcbiAgICBjb25zdCBwYWdlID0gaW5qZWN0KCd2aWV3JylcbiAgICBcbiAgICByZXR1cm4gKCkgPT4ge1xuICAgICAgY29uc3QgY29tcG9uZW50ID0gcGFnZS52YWx1ZSAmJiBoKHBhZ2UudmFsdWUsIHsgcmVmOiB2aWV3UmVmIH0pXG4gICAgICByZXR1cm4gY29tcG9uZW50XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgXG5cdFx0fVxuICB9XG59IiwiUGFnZUEudnVlIjoiPHRlbXBsYXRlPlxuICA8cD5cbiAgICBQYWdlIEFcbiAgPC9wPlxuPC90ZW1wbGF0ZT4iLCJQYWdlQi52dWUiOiI8dGVtcGxhdGU+XG4gIDxwPlxuICAgIFBhZ2UgQlxuICA8L3A+XG48L3RlbXBsYXRlPiJ9) will yield the same result **when used in a dev environment** (it works on the SFC playground because it runs in production mode). Can you open an issue on vuejs/core without the router (using the code I shared)?
