### ISSUE TITLE
`{}` should be URI encoded when used in query string

### ISSUE THREAD

**Issue by CarterLi** [vuejs/router#1412]
### Version
4.0.15

### Reproduction link
[https://n/a](https://n/a)

### Steps to reproduce
[encodeQueryValue](https://github.com/vuejs/router/blob/87d09f81ba11a9153af45836f4b10a5736257cae/src/encoding.ts#L95) explicitly decoded percent-encoded `{}` back to character.

However, according to [the spec](https://en.wikipedia.org/wiki/Query_string#URL_encoding) `{}` should be encoded

```
* Characters that cannot be converted to the correct charset are replaced with HTML numeric character references[13]
* SPACE is encoded as '+' or '%20'
* Letters (A–Z and a–z), numbers (0–9) and the characters '~','-','.' and '_' are left as-is
* + is encoded by %2B
* All other characters are encoded as a %HH hexadecimal representation with any non-ASCII characters first encoded as UTF-8 (or other specified encoding)
```

> **All other characters are encoded as a %HH hexadecimal representation with any non-ASCII characters first encoded as UTF-8**

`URLSearchParams` will encode `{}` too

```js
new URLSearchParams({ a : '{}'}) + '' // => 'a=%7B%7D'
```

### What is expected?
`{}` should be encoded

### What is actually happening?
`{}` is not encoded

**Comment by CarterLi** [comment]
This issue breaks tomcat when passing JSON object using query string: `java.lang.IllegalArgumentException: Invalid character found in the request target [/?a={ ]. The valid characters are defined in RFC 7230 and RFC 3986`

https://github.com/apache/tomcat/blob/8e2aa5e45ce13388da62386e3cb1dbfa3b242b4b/java/org/apache/coyote/http11/LocalStrings.properties#L47

encodeURIComponent is not only safer, but also faster than regex replacement. Please use it

**Comment by CarterLi** [comment]
vue-router 3 does use encodeURIComponent: https://github.com/vuejs/vue-router/blob/dev/src/util/query.js#L13

Therefore this is considered a.breaking change

**Comment by posva** [comment]
This change was necessary to have consistent behavior across different browsers (https://router.vuejs.org/guide/migration/#route-properties-encoding) which was missing in Vue Router 3. As you can imagine, the line wouldn't have been added otherwise 😄 . The URLSearchParams is not supported for every supported browser by Vue so it's normal it's not used yet. **This is actually a bugfix that couldn't be implemented any other way than a breaking change**.

BTW, the mentioned article in Wikipedia is not the spec. The spec is on whatwg.org. You can find the links on the [encoding.ts](https://github.com/vuejs/router/blob/87d09f81ba11a9153af45836f4b10a5736257cae/src/encoding.ts) file if you are curious 🙂 

If you specifically need this because your server handles queries in a specific way, you can customize the `stringifyQuery` option and even reuse the one exported by Vue Router. 

However, note that nothing prevents a user from entering a URL with `{}` characters and the browser will **not encode it before sending it to the server**:

![Screenshot 2022-05-23 at 14 30 45](https://user-images.githubusercontent.com/664177/169819693-75743b84-071b-4dc1-a716-03b8142aa0a3.png)
e
This is Edge 101

Vue Router is only making this consistent during client side navigation but the error you see in tomcat will appear without tomcat anyway.
