### ISSUE TITLE
Infer routes without using `as const`

### ISSUE THREAD

**Issue by HunYan-io** [vuejs/router#1444]
### What problem does this feature solve?
This allows users to omit the `as const` when passing the routes array to `createRouter` options, which results in better DX imo.

### What does the proposed API look like?
This might be possible thanks to this issue comment in typescript
https://github.com/microsoft/TypeScript/issues/30680#issuecomment-752725353

Here is how I think this could be implemented

```ts
type Cast<A, B> = A extends B ? A : B

type Narrowable = string | number | bigint | boolean

type Narrow<A> = Cast<
  A,
  [] | (A extends Narrowable ? A : never) | { [K in keyof A]: Narrow<A[K]> }
>

interface RouteRecordRaw {
  path: string
  name: string
}

interface RouterOptions<Routes extends ReadonlyArray<RouteRecordRaw>> {
  routes: Narrow<Routes>
}

function createRouter<Routes extends ReadonlyArray<RouteRecordRaw>>(
  options: RouterOptions<Routes>
) {
  return options
}

const router = createRouter({
  routes: [
    {
      path: '/',
      name: 'home'
    }
  ]
})
```

The types are recursive but it's possible to change them in a way that infers only the routes array in case there is a nested array that should not be inferred.

**Comment by posva** [comment]
Thanks, this is interesting! I think that given the status of that API being experimental and how easy `as const` makes it to stop or start using it, I rather keep it until it gets out of its experimental state. After all, I don't want to force everybody use this experimental API because it has performance implications with large amounts of routes, due to the nature of the types and it would make the fastest computer lag 😆 

I didn't know you could narrow a const type like this, It does work with arrays. It's a good trick to remember.
