### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'parentNode') 

### ISSUE THREAD

**Issue by lpk3nny** [vuejs/router#1454]
### Version
4.1.0

### Reproduction link
[jsfiddle.net/Lw1evucg/](https://jsfiddle.net/Lw1evucg/)

### Steps to reproduce
1. Click "Bar"
2. Click "Foo"

### What is expected?
Router shows Foo page. Application continues working

### What is actually happening?
Routing stop working after getting error:
```
vue@next:9310 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (vue@next:9310:32)
    at ReactiveEffect.componentUpdateFn [as fn] (vue@next:7134:19)
    at ReactiveEffect.run (vue@next:613:27)
    at instance.update (vue@next:7166:58)
    at callWithErrorHandling (vue@next:1733:38)
    at flushJobs (vue@next:1967:19)
```

**Comment by posva** [comment]
You are using outdated version:

```html
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/vue-router"></script>
```

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
