### ISSUE TITLE
Memory Leak - Detached Dom Element On Every Route

### ISSUE THREAD

**Issue by michaelperel** [vuejs/router#1489]
### Version
4.1.2

### Reproduction link
[blogs.windows.com](https://blogs.windows.com/msedgedev/2021/12/09/debug-memory-leaks-detached-elements-tool-devtools/)

### Steps to reproduce
Use the demo app that gets installed when you run:

`npm init vue@3`

(say yes to installing the router)

Repeatedly click "Home" and "About" routes. In Chromium Edge devtools, select "Detached Elements"

Notice that every click results in a new detached element (the view that was being switched away from). When you click the garbage icon, and the refresh icon, note that these detached elements are never garbage collected.

### What is expected?
Properly garbage collected html elements

### What is actually happening?
Elements are being retained, not garbage collected. A memory leak occurs as a result.

<img width="1127" alt="memory_leak" src="https://user-images.githubusercontent.com/10049607/181154644-3c993a34-4368-4935-b07e-782271199128.PNG">

This may be somewhat related to #730 . It was closed without resolution.

---
This causes problems for long running SPAs. For instance, I built a PWA and after a few days, it must be reloaded.

**Comment by posva** [comment]
Hello! I checked again using the reproduction from the previous issue and it didn't yield any memory leaks.

I also tried creating a new project with `npm init vue`, building for production and serving the dist folder. Same result: node count is stable.

![Screenshot 2022-07-27 at 09 29 47](https://user-images.githubusercontent.com/664177/181188116-3dfddf33-2131-4b43-88ac-059dd39b5728.png)
![Screenshot 2022-07-27 at 09 29 57](https://user-images.githubusercontent.com/664177/181188118-49a7cf30-9bdd-459e-93eb-04fa604ffd5a.png)
(Edge 103)

As you can see only one about page is cached (probably for performance reasons by the browser or Vue) and the home page isn't (probably because it's only one node)

These are the components I tried (simplified after creating the project) so you can check it yourself:

App.vue
```vue
<template>
  <header>
    <div class="wrapper">
      <nav>
        <RouterLink to="/">Home</RouterLink>
        <RouterLink to="/about">About</RouterLink>
      </nav>
    </div>
  </header>

  <hr />

  <RouterView />
</template>
```

HomeView.vue
```vue
<template>
  <main>Home</main>
</template>
```

AboutView.vue
```vue
<template>
  <div class="about">
    <h1>This is an about page</h1>
  </div>
</template>

<style>
@media (min-width: 1024px) {
  .about {
    min-height: 100vh;
    display: flex;
    align-items: center;
  }
}
</style>
```

Keep in mind you could also have an extension creating memory leaks.

Also please don't open issues without a reproduction. Especially memory leak issues. Always provide fully boiled down reproductions that lead to memory leaks.
