### ISSUE TITLE
if  project  has    vite.config.ts  or  vue.config.js   ,  make  createWebHistory  auto read  config's  base

### ISSUE THREAD

**Issue by hxzAugustinus** [vuejs/router#1509]
### What problem does this feature solve?
when we  use  config's  base  ,  we  can  keep  the same  with   router's  base 

### What does the proposed API look like?
createWebHistory(){

if(  has.config.base ){
   base =config.base
}

}

**Comment by posva** [comment]
You can use an env variable.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by hxzAugustinus** [comment]
ye , we can  use   env variable like vite(import.meta.env.BASE_URL) !
in fact , people first time add config's base but  forget add the createWebHistory  parameter in most cases ,
so i think it will be simpler and  smarter to  use  for new coder
