### ISSUE TITLE
Listen to the route. Why is there no from

### ISSUE THREAD

**Issue by message163** [vuejs/router#1532]
### Version
4.1.4

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/modest-jepsen-drro1s)

### Steps to reproduce
import {watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
watch(route,(v)=>{
    console.log(v)
})

### What is expected?
You want the from source attribute

### What is actually happening?
There is no such attribute

**Comment by posva** [comment]
A watcher is not a navigation guard: https://router.vuejs.org/guide/advanced/navigation-guards.html#navigation-guards

--- 

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
