### ISSUE TITLE
Effects are re-executed when leaving a page

### ISSUE THREAD

**Issue by adamjedlicka** [vuejs/router#1562]
### Version
4.1.5

### Reproduction link
[jsfiddle.net/djw2mbhk/](https://jsfiddle.net/djw2mbhk/)

### Steps to reproduce
When going from one page to another (category.vue to product.vue), effects from the old page are executed. Watch does not behave this way as fixed in here: https://github.com/vuejs/core/issues/2291 

### What is expected?
When switching from one page to another, only effects from the new page are executed.

### What is actually happening?
When switching from one page to another, effects from both pages are executed.

**Comment by posva** [comment]
This is expected as effect is immediate and the [same behavior happens in vue](https://sfc.vuejs.org/#eNrVU8GOmzAQ/ZWRL7ASwVL3UAlBmiD1XvVsKWLBsN6AbRlDDhH/3jEmlCTVHnrbQxQe82ae5/lxJUet43HgJCFpXxqhLfTcDnrPpOi0MhauYHgdgTZqFBWPoCvM+XdxgQlqozoIsDlgEmChn34VDT8utZjOyAk8cfI7Tr5y3K9UsrfgJ2U3xdCPfrkn5I+EHAlMeoJGjHVcILz1um6AepClFUqCVU3T8vAFrr4Ac088Fu3gOrcgy5YT/ViEE4994zT/LS6FwSj4JUDXkICiKfXeoqsILO90W1iOCCB9G6zFgxzKVpTnjBF/Ikb2/iGlnuDJpUIHJZcWEtEj2c1HakrXAvJSuiqQiHjPd12h449eSbzoeVW2FHpGktvyjOAlOMzIu7W6TygdpD43MU6nB6xRM0grOr6rVHd4jb/Fr99pJXq7fR/zvtu9GXXpuUFFRqLNcIovR252hsuKG24+FXvg3gk+1J5EnSZeyYQGrBH8R8bXSF5ByA9e2gguhS3fI+B1/Rf+nMFT5B9i5icsdz/HdN5bbkaEmLRs7/12varlcauaMJg5fvxxyY3PXXw6yaJzIZo+CxKzqd67TeGYUrfZJgRMLi7MH9kXcSEP4P9sqMTojchTjMr4ZMX0B6WhrXQ=). This is because they are immediate so [the same happens with `immediate: true`](https://sfc.vuejs.org/#eNrVU02PmzAQ/SsjX8JKBEvdQyVE0gSp96pnSxELk6w3+EPGkEPEf+8YkzQf1Z562QOC8byZ53nzOLOttdnQI8tZ0dVOWg8d+t6uhZbKGufhDA73KVhnBtlgCqpyx9/VCUbYO6NgQcULoQFm+O5XdcDtnMv4FAWCJ0x5hymvmPDURnceYqfVhTGJrV/uAeUjoCSA0BFgKaY8DZBcakM1wL7XtZdGgzeHQ4vJC5xjAqaabKjaPlTeBqvVfKMfM3Ee41g4Tq9ZpWQxSDwtSDUCEGnBo7akKgUelW0rjxQBFG+993SRTd3K+rgSLN5IsHX8KHgERHBtSEGN2kMuOwKH/gQt+DVBuIJfGVjKouZLVdnsozOaFj2NKuZEJ1h+GV4wWkKIBXv33nY55722x0NG3fmGctz12kuFy8aozWv2LXv9zhvZ+dvzDDu1fHPm1KEjRsHSm+acDgd0S4e6QYfuU7IH7B3hQ+6JNHDSSkYS4GrBf3j8askzSP2BtU/hVPn6PQXc7/+GP6fgyfIPNosd5t1PNp3m1lOLJIBSIKet1lHvUGtazFpzSBYTJrbfzr6Jvst2O12pYKIxDbdUChtJq83BO3Ll+Jm7hC/sOowP24KHcW+cIfQszfTnfRFpyv8pTSOHKE5ZkKeGJ3nGP97YuyY=). Use a regular watch or `flush: 'post'` instead and it will work as described in the issue even with vue-router in your reproduction
