### ISSUE TITLE
parent router component without path

### ISSUE THREAD

**Issue by coader** [vuejs/router#1625]
### What problem does this feature solve?
some router just is container for children, so it not need any path to visit

### What does the proposed API look like?
    // path:'empty',
    component: MainLayout,
    children: [
      {
        path: '/',
        component: Home,
      },
]

**Comment by coader** [comment]
I already set the parent as '/' also. and it looks works

**Comment by posva** [comment]
at the root, set the path to `/` and within nested routes set it to an empty string `''`. Given the importance of the `path` property, I don't think it makes sense to allow omitting it for layout purposes since there are already other ways to achieve that like using the MainLayout component directly in your pages. This would make the route records even more confusing to people
