### ISSUE TITLE
router-link should provide an attribute to specify route locations that count as exact active

### ISSUE THREAD

**Issue by jez9999** [vuejs/router#1746]
### What problem is this solving

I have a router setup like so:

```
		{
			path: '/help',
			component: Help,
			children: [
				{
					path: '',
					name: 'Help',
					component: Quickstart,
				},
				{
					path: 'quickstart',
					name: 'Quickstart',
					component: Quickstart,
				},
				{
					path: 'about',
					name: 'About',
					component: About,
				},
				{
					path: 'contact',
					name: 'Contact',
					component: Contact,
				},
			]
		},
```

On the Help page, I have a set of tabs that are `router-link`s linking to Help, About, and Contact.  But both the Help and Quickstart routes map to my Quickstart component; I want the link to be "exactActive" for both of them.  At the moment, I have to specify one or the other for my `router-link`'s `to` attribute, and that one will cause "exactActive" (as well as `aria-current` to get set), but I want both to cause it.

### Proposed solution

`router-link` should provide an attribute like `active-routes` where you can specify a list of route locations (ie. `RouteLocationRaw`s) that could as "exact active", and cause the "exactActive" class to get set as well as the `aria-current` attribute.  In the above example, I could specify both `Help` and `Quickstart` for my main help link.

**Comment by posva** [comment]
Exact active and active links already means something in the context of the router. Changing it the way you are proposing would add extra meaning that can be changed by the user, make it confusing.

In order to achieve what you want, you can directly set the aria attributes that are relevant to your application. You can even create a custom RouterLink implementation (see docs) to automatically add the aria attributes. In order for Vue Router to not add the wrong aria attributes, we intentionally limit it to `aria-current=page` (which can be customized). **Note that only one element should have the `aria-current=page`**.

**Comment by jez9999** [comment]
@posva Why on earth did you close the discussion #1736 ?  It's unrelated to this issue.  Re-open it NOW!  Why is the attitude of vue-router to just close everything down?  It's infuriating!
