### ISSUE TITLE
Optional parameters are not identified consistently (different on page load vs navigation)

### ISSUE THREAD

**Issue by hidde-jan** [vuejs/router#1759]
### Reproduction

https://stackblitz.com/edit/vue-y9jlxy?file=package.json,src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue,src%2Fmain.js

### Steps to reproduce the bug

1. Open example
2. See that the 'A' RouterLink only has an active match (observe URL hash)
3. Navigate to 'B' or 'C'
4. Navigate back to 'A', it will have an exact active match (with the same URL hash as before)
5. Optionally check console output to observe the value of useRouter().currentRoute.value.params

### Expected behavior

The 'A' RouterLink (to route without the optional parameter) should be an exact match on page load.

### Actual behavior

On page load, the route interprets `#/` as having { parameter: '' } as params, on subsequent navigation, it will have an empty object as params.

### Additional information

I'm pretty sure this bug is present for both createWebHashHistory and createWebHistory. I ran into this because a certain link did not have an active match on page load, but did after navigating away and back.

Additionally, https://new-issue.vuejs.org/?repo=vuejs/router does not actually work. I needed to copy paste everything I entered there to create this issue, even though I was pointed to that site when trying to create a new bug report.

**Comment by posva** [comment]
This is indeed a bit confusing but it is an edge case of optional params and necessary for correct active matching. By passing the object route notation, you are explicitly passing an empty object of params. But this makes the link A active because it is indeed a subset of the B or C link (both have a param). If you explicitly pass the param you will see the correct behavior of having exact active:

```vue
<RouterLink :to="{ name: 'my-route', params: { parameter: '' } }">A</RouterLink>
```

In this case, exactly one link is active and exact active at a time, which is the correct behavior given the route. From the router perspective, an empty optional parameter is an empty string. Not passing the parameter produces the same path but it creates two different resolved routes (empty params vs not empty params), which is why they are not exactly active.

If you do need to have the A as active while B and C are exact active, you need to change the structure of the routes:

```ts
const router = createRouter({
  history: createWebHashHistory(),
  routes: [
    {
      path: '/',
      children: [
        { path: '', name: 'my-route-p', component: HelloWorld },
        { path: ':parameter?', name: 'my-route', component: HelloWorld },
      ]
    },
  ],
});
```

This also requires you to differentiate the A from B and C routes

---

The issue helper is not used anymore. When creating an issue you now get a form directly on GitHub: https://github.com/vuejs/router/issues/new/choose
