### ISSUE TITLE
Safari back history titles not written, when using HTML5 history 

### ISSUE THREAD

**Issue by dobromir-hristov** [vuejs/router#1816]
### Reproduction

https://codesandbox.io/s/cold-tree-vb8sku?file=/src/router.js

### Steps to reproduce the bug

1. Use Safari
2. From the repro link, go to the deployed preview website - https://vb8sku.csb.app/
3. Click on the links a few times in the page
4. Assert that when you hold down the back arrow in the browser, to see the list of history items, none of them have titles.

### Expected behavior

Page titles should be stored in the Safari history, when holding down the back arrow

### Actual behavior

Titles are lost and we only see the urls instead. This only happens in Safari.

![image](https://user-images.githubusercontent.com/9863944/234263921-62cfc76d-716a-4a0c-89e5-a8d20c6c2aae.png)

### Additional information

This is caused by passing an empty string as a second parameter in the `replaceState/pushState` methods. 

https://github.com/vuejs/router/blob/fb2bef43232badd41dd28d01f7efeb4f957e61e8/packages/router/src/history/html5.ts#L232

I know that MDN suggests the second param is `unused`, but Safari does in fact use it. If we pass `document.title` instead, like in Vue Router 3, this problem is no longer there.

**Comment by posva** [comment]
It's not just that MDN suggests it, it's per spec 😅 (https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-history-interface). This is more of a Safari bug: it could maybe fallback to `document.title` if an empty value is passed. That way it would just align with other browsers.

BTW v3 also passes an empty string: https://github.com/vuejs/vue-router/blob/3d026ea14f8f8fd93da73889d2bcd2103d44bec7/src/util/push-state.js#L37.

Also, setting it to `document.title` would mark it with the title of the current page instead of the upcoming page, so it would be even more confusing. I'm open to suggestions but given the niche case, they must be very lightweight and functional and I don't think there is any without changing the existing API. One could always implement a custom history that overrides that value though

**Comment by dobromir-hristov** [comment]
Hmm... this is not an issue with router v3, but you are right, an empty string is also passed there.

Compared to V3, could it be the extra `replace` that is called, to add metadata to the page? - https://github.com/vuejs/router/blob/main/packages/router/src/history/html5.ts#LL288C5-L288C5

**Comment by posva** [comment]
Maybe! It is a really important line though, so it cannot be removed.

Given how this is a Safari-specific behavior (or bug) I can't really tell. If you really care about this, I think you can give it some research and maybe there is something that could be improved in vue router. Otherwise, I think we will have to hope for Safari to fix it and align with other browsers (usually works as an argument if you open a ticket in webkit).

I'm closing this as a wontfix but will keep an eye on comments if anything changes and makes it possible to fix!
