### ISSUE TITLE
Support disabled prop

### ISSUE THREAD

**Issue by ivos** [vuejs/router#1818]
### What problem is this solving

I repeatedly come across situation where I need a piece of UI to link to another screen conditionally, i.e. on some condition it should not link, just display the content.

### Proposed solution

It would be great to be able to just set `<router-link ... :disabled="some condition...">...</router-link>`.

### Describe alternatives you've considered

I've already created a component for that:

```
<script setup>
defineProps({
  disabled: { type: Boolean, default: false }
})
</script>

<template>
  <div
    v-if="disabled"
    v-bind="$attrs"
  >
    <slot/>
  </div>
  <router-link
    v-else
    to=""
    v-bind="$attrs"
  >
    <slot/>
  </router-link>
</template>
```

**Comment by posva** [comment]
At the moment, creating a custom component to add this custom behavior seems like the right decision because:

- There are different possible meanings for a disabled prop (or any other name) on a router-link
- There are accessibility implications to invalid links

If you manage to solve these questions, it could be worth writing a detailed RFC in the rfcs repository to propose the idea to vue-router
