### ISSUE TITLE
Volatile Parameters (not reflecting in url)

### ISSUE THREAD

**Issue by cleverplatypus** [vuejs/router#1928]
### What problem is this solving

Sometimes it's useful to pass parameters to a route that are relevant only in programmatic navigation and that shouldn't be in History manager nor applied when reloading the page.

This could be use to one-off activation of features in the target route's view that aren't wanted as a side effect of just loading the page. (Think of the infamous page reload warning after an HTTP POST).

### Proposed solution

Having a separate dictionary of optional values that can be consumed by the target route and acts as a "message" to the target route.

Because `options` values don't reflect in the URL, reloading the page won't pass the message again.

```js
   route.push({
      name: 'tests-screen',
      options: {
         autoRunTests: true
      }
   })
```

### Describe alternatives you've considered

There are workarounds such as (neater to dirtier):
- sending some kind of event/signal on route navigation success
- passing a query param, catching the param from the target route and then calling route.replace removing the param
- setting the parameter in a model/store,  reading it from the target route and then resetting it

However none of the above solutions are neat enough IMHO.

**Comment by posva** [comment]
Navigation state that is lost upon refresh was intentionally removed and advised against since v2

But there are plans to align with the navigation api once it’s stable and bring transient info https://developer.mozilla.org/en-US/docs/Web/API/NavigateEvent/info which only exists during the navigation but can be saved in other places. There is also the possibility to pass history state right now and write to meta during a navigation guard (which does what you want)
