### ISSUE TITLE
 [Vue Router warn]: Finding ancestor route "/:path(.*)*" failed for "/:path(.*)*"

### ISSUE THREAD

**Issue by rex-ll** [vuejs/router#2266]
### Reproduction

RT

### Steps to reproduce the bug

After upgrading to the latest version

`
{
  path: '/:path(.*)*',
  name: PAGE_NOT_FOUND_NAME,
  component: LAYOUT,
  meta: {
    title: 'ErrorPage',
  },
  children: [
    {
      path: '/:path(.*)*',
      name: PAGE_NOT_FOUND_NAME,
      component: EXCEPTION_COMPONENT,
      meta: {
        title: 'ErrorPage',
      },
    },
  ],
}
`

### Expected behavior

no warning

### Actual behavior

warning log

**Comment by skirtles-code** [comment]
I think I managed to reproduce this:

- [Playground](https://play.vuejs.org/#eNqNVW1v2zYQ/iucOsBKZ0uOU/SDprrpimDZsJegLfZl6gdaOltsKFIjKceB4f++I6k3O062BLape33unjtqH1SUieibDpKAVbVUhuxJroAa+FDX5EDWSlZksm1gkonWQMnGgGo1UewfB7X163S0riPvm4k+aoifi0wQEjUaQu/unyvZCBNOXqHb5CKYBq07YksNVDVH/6U1TMvL5S1wLm2y79IYH524dj940EZJsVl+bJQC0SImNTVlksatjuz35HuniNYN53eoJIeDCxP7OKmg2y7gJ4fyNybuiZHvsiDOguXPEs/kVlaQxoP+WQ+6Qknv9sE+PfFL4y5nank5jvUXgwcSt3atOo37xmC/fC/Psvk7VFI93jJt8GfaCn3cMcuzns2eT1ugS92R2glaZjvabUFHdr1kGAEpdMuGJu/I37aUva/RkUMmcWIPYfT64vVk6jWCVoAauso7SS4xpUBikx5cq6nA0ARrNsxw63SjlFR3dAOTKTl03iXjBY5F4vPbvxbDyzjOYznB09c8Uv8fUKQ/fXW/OIhfTzqmsGNj2kKHuvSMJudoDi9cLN9vPB5wyzIBO8dXAWva8C42Ds+YVrtxOlesNjhjJw4uLdZUykJjWR71Rn6RrvbwYuimQXCR3zEV1Y0uw4nfgolb965m+4314mZ2GfHhZN8Xyw4ebvvCC1eNMVKQ65yz/B43rMdwumTe8Mm2HM3nUDHRYBp7AwwbhPxiDcX563BP8BpzlEz707M7dcJnbx9iR0a6kcpqOp0GqvLSzkGLyM/ABkZtV4heCR8m+qcB9Ri1bu/fkwmC6NqOZYZeM/h6qhRgj3II98T529ltQxyInSE3nvbwH5T1DR4443QFvL3WPruYCUmZwGLIdlbJAnhkFKuQTZ8xC0hFdxzExpQoXMyRW38BdpGOOfWczCpa4y0oBbLqSstahc6CfmSzYODGirOgNKbWSRw3or7fRNjjeLC4fhNdRVdxgZs1kkagq9lKyQftrt0saJc4C67RKC5ga6TkekZr9lyKJ4bXb6O30WXM2SrG6DETBexc7K7xWKbROBBrtjkp0o4F46D+rA3DgTkqluLr8uFXJzOqgR5oXkJ+f0b+Te885DsFWN0WRsUZqnDmvPrm8x+ww3OvRBYbjtYvKD+BlryxGL3ZT40oEPbIzqH9xXHGxOaLvtkZELorygIdBtkR+fGF0ge4V9GbURe1eeSgo1zb9yW+eKc4a0x4v5VUBaiELOodQbCsIK/m8/mP7u7DcEzMVhJvlSohl/N65+Q1LQoE20swSyYwLFkSSn7Aj785vTeHNb4uxpblYpx5CD8AyPN8BCAhc/xftBGCw7+ZMEQW)

But it only happens if there are two routes with the same `name`. This is probably something that should be handled better, but is there any reason why you need two routes with the same name? You should be able to avoid this warning just by removing the `name` option from the parent route.

**Comment by posva** [comment]
names must be unique, this is what you need to write instead:

```ts
{
  path: '/:path(.*)*',
  component: LAYOUT,
  meta: { title: 'ErrorPage' },
  children:
    [
      {
        path: '',
        name: PAGE_NOT_FOUND_NAME,
        component: EXCEPTION_COMPONENT,
        meta: { title: 'ErrorPage' },
      },
    ],
}
```

**Comment by sherleysong** [comment]
How can i make / to Home , make /foo to Foo , while all the left "/:pathMatch(.*)" to PAGE_NOT_FOUND ?

**Comment by CDwenhuohuo** [comment]
谢谢
